version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    volumes:
      - ./.wwebjs_auth:/root/.wwebjs_auth
    restart: unless-stopped
